   
   <div class="policy_pages">
        <div class="auto_container">
            <div class="policy_pages_detail">
                <div class="policy_pages_content">
                    <h1>Privacy Policy</h1>

                    <p class="pt-3"><b>THIS PRIVACY POLICY (“POLICY”) DOCUMENT IS AN ELECTRONIC RECORD IN
                            TERMS OF THE INFORMATION TECHNOLOGY ACT, 2000, AND THE RULES MADE
                            THEREUNDER. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM
                            AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.</b></p>
                    <p><b>THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF
                        INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER AND
                        CONSUMER PROTECTION (E-COMMERCE) RULES, 2020 THAT REQUIRES PUBLISHING
                        THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS OF USE FOR ACCESS
                        OR USAGE OF THIS WEBSITE.</b></p>

                        <p>These Policies apply to the use of the website bizionictech.com., its mobile-optimized version and other
                            media formats (collectively referred to as the “<b>Platform</b>”) </p>
                        <p>The Platform is owned by Bizionic Technologies & Marketing Solutions Private Limited (including its
                            parent company, subsidiaries, employees, officers, agents or affiliates), a private limited company
                            incorporated under the provisions of the Companies Act 2013, with the office at Bizionic Technologies &
                            Marketing Solution Private Limited, 3rd Floor, Office No 1A, 6-3-1090/B/4, The Grand Building, KFC
                            Building, Raj Bhavan Rd, Somajiguda, Hyderabad, Telangana 500082 and holding CIN:
                            U72900TG2022PTC164876 (hereinafter referred to as the “<b>Company</b>”). The Platform provides
                            Technology, Marketing, Project management, Hiring, Resources Procurement, Management and Payroll
                            services, which enable users to access the Services through the web and any number of device types (e.g.,
                            desktop, laptop, tablet, and smartphone devices) you choose.</p>
                        <p>By registering, accessing or using the Platform and its services, content, technology or features, you agree
                            to accept our Privacy Policy. By accepting this Policy, you understand and agree to the collection, use,
                            sharing and processing of personal information described herein. If you accept this Policy on behalf of
                            another person, company, or other legal entity, you represent and warrant that you have full authority to
                            bind such person, company or legal entity to these terms. If you provide the Company with personal
                            information about someone else, you confirm that (a) such information is accurate and up-to-date; (b)
                            such person is aware that you have provided their information; and (c) they consent to both the disclosure
                            and the use/processing of their information in accordance with this Policy. This Policy applies to all
                            current and former visitors, users and others who access this Platform.</p>
                        <p>In the event you are located in the European Union (“<b>EU</b>”) or European Economic Area (“<b>EEA</b>”), You
                            will be asked to provide explicit and affirmative consent to the collection, processing, and sharing of
                            Your Personal Information (as defined hereinafter), subject to withdrawal of your consent at any time on
                            request. We will not share any Personal Information with any third party without your consent, except as
                            outlined in this Privacy Policy or as permitted by law.</p>
                        <p>This Privacy Policy is intended to comply with Regulation (EU) 2016/679 of the European Parliament
                            and of the Council of 27 April 2016 on the Protection of Natural Persons with regard to the Processing of
                            Personal Data and on the Free Movement of such Data (hereinafter referred to as the “<b>General Data
                            Protection Regulation</b>” or “<b>GDPR</b>”) in so far as our services result in collection and/or processing of
                            Personal Information (as defined hereinafter) of users who are in the EU and EEA to provide appropriate
                            protection and care with respect to the treatment of such information in accordance with the GDPR. </p>
                        <p>Those who access the Platform from outside India are responsible for compliance with local laws if and to
                            the extent local laws are applicable.</p>


                            <ul class="pt-3">
                                <li>
                                    <h6>1. Scope of this Policy</h6>

                                    <ul>
                                        <li><p>1.1. This Policy is an electronic record in the form of an electronic contract formed under the
                                                Information Technology Act, 2000 and the rules made thereunder. This Policy does not require any
                                                physical, electronic or digital signature. </p></li>
                                        <li><p>1.2. By accessing or using the Platform or otherwise giving us your information, you undertake that you
                                            have the capacity to enter into a legally binding contract vide. This Policy constitutes a legally
                                            binding document between you and the Company under the applicable law, particularly the Indian
                                            Contract Act, 1872. </p></li>
                                        <li><p>1.3. Please read the terms and conditions of this Policy carefully before accessing or using this
                                                Platform. This Policy describes the types of information the Company collects, why and how the
                                                Company uses the information, with whom the Company shares it, and the choices you can make
                                                about the Company’s use of the information. This Policy also describes the measures the Company
                                                takes to protect the security of the information and how you can contact the Company about its
                                                privacy practices. </p></li>
                                        <li><p>1.4. This Policy describes the Company’s current data protection policies and practices and may be
                                                amended/updated from time to time. Any changes to this Policy will become effective upon posting
                                                the revised Policy on the Platform. You should regularly check this Policy to apprise yourself of
                                                any updates. Your continued use of the Platform or provision of data or information thereafter will
                                                imply your unconditional acceptance of such updates to this Policy.</p></li>
                                    </ul>
                                </li>

                                <li>
                                    <h6>2. Consent</h6>

                                    <ul>
                                        <li><p>2.1. By mere use of the Platform, you expressly consent to the Company’s use and disclosure of your
                                                Personal Information (as defined below), including SPDI (as defined below) and third-party
                                                information in accordance with this Policy. If you do not agree with the terms of this Policy, please
                                                do not use the Platform. </p></li>
                                        <li><p>2.2. In case you wish to avail of any or all of the intermediary services provided by the Company on the
                                                Platform, the Company shall provide a username and password to you (“<b>Login Credentials</b>”) as
                                                set out in the Terms of Use. You may be required to fill in the Information on the Platform,
                                                including full name, email address, user name, password, and activation links sent to the registered
                                                email to set up your account on the Platform. You hereby explicitly agree that the Terms of Use
                                                shall govern your use and access of the Login Credentials read with the terms of this Policy and
                                                any other agreement that you may enter into with the Company. You should not share your Login
                                                Credentials, one-time password or additional security information for your account with anyone. If
                                                we receive ins</p></li>
                                    </ul>
                                </li>

                                <li>
                                    <h6>3. Our Commitment</h6>

                                    <ul>
                                        <li><p>Company understands the importance and sensitivity of all personal and other information and
                                            respects your privacy whether browsing or conducting transactions on the Platform. We are
                                            committed to handling all your personal information in accordance with the Indian laws on data
                                            privacy and security. We strictly abide by the "reasonable, relevant, and necessary principles" to
                                            collect your personal information, and do not collect information that is prohibited by such laws
                                            and regulations.</p></li>
                                    </ul>
                                </li>



                                <li>
                                    <h6>4. Types of Information </h6>
                                    <ul>
                                        <li><p>4.1. Following are the types of information shared by you or collected by Company about you or your
                                                usage of the Platform, on and through the Platform:</p>
                                            
                                            <ul class="ml-4">
                                                <li><p>4.1.1. <b>Personal Information:</b> Personal Information means any information that may be used to
                                                        identify an individual, including, but not limited to, the first and last names,
                                                        billing/alternate address, state, ZIP/Postal code, city, telephone number, mobile number,
                                                        date of birth, age, gender, e-mail address, or any other information. The Company limits
                                                        the collection of Personal Information which is necessary for its intended purpose. </p></li>
                                                <li><p>4.1.2. <b>Non-Personal Information:</b> Non-Personal information means information that does not
                                                        specifically identify an individual, but includes information such as your IP address, the
                                                        date and time you access the Platform, amount of time you spend on the Platform, your
                                                        browsing history (recorded by the text and graphics files that compose that page), the
                                                        internet address of the Platform from which you linked directly to Platform, devise
                                                        location, information about your mobile devise including hardware model, preferred
                                                        language, unique devise identifier, information and other such information. The Company
                                                        may also collect Non-Personal Information that you voluntarily provide, such as
                                                        information included in response to a questionnaire or a survey conducted by the
                                                        Company.</p></li>
                                                <li><p>4.1.3. <b>Financial Information:</b> Financial information including bank account details,
                                                        credit/debit card details or such other payment information. Further, sensitive personal
                                                        data or information (“<b>SPDI</b>”) of a person includes Personal Information about that person
                                                        relating to: passwords, financial information (bank accounts, credit and debit cards or
                                                        other payment instruments), physical information including GPS location, device ID. This
                                                        information may also include details you provide when making online transactions. This
                                                        may include your payment instrument number (e.g., credit card), your name and billing
                                                        address, as well as the security code associated with your payment instrument (e.g., the
                                                        CSV or CVV). You hereby acknowledge and agree that the payment data, to the extent
                                                        consisting of details related to the manner and mode of payment of fees for the use of the
                                                        Platform and services (such as details of your bank account, credit card, debit card, net
                                                        banking, etc.), submitted by you while making payment of fees: (i) goes through the safe
                                                        and secure transaction process provided by our third party payment gateway partners; (ii)
                                                        goes through the Visa or MasterCard pages, as the case may be, based on your payment
                                                        method(s) in order to prevent any misuse of your payment details; and (iii) that such
                                                        payment details are not shared with the Company and third parties or any other users of
                                                        Platform.</p></li>
                                                <li><p>4.1.4. <b>Information from Third Parties:</b> Company may receive information about you if you
                                                    use Platform, including any other services we may provide. We are also working closely
                                                    with third parties, including but not limited to, business partners, service providers,
                                                    advertising networks, analytics providers, and search information providers. We may
                                                    receive information about you from such third parties. This information may be combined
                                                    with the other information you provide to us.</p></li>
                                                <li><p>4.1.5. <b>Usage Information:</b> Usage Information includes without limitation all data and
                                                        information collected automatically through the Platform (or through the third party
                                                        analytics service providers), by use and access of the Platform in the nature of system
                                                        administrative data, statistical and demographical data, and operational information and
                                                        data generated by or characterizing use of the Platform including without limitation, NonPersonal Information, cookies, your search queries, comments, search results selected,
                                                        number of clicks, pages viewed and the order of those pages, error logs, Platform traffic,
                                                        time spent on the Platform, number of visits to the Platform and other similar information
                                                        and behaviour indicating the mode and manner of use of the Platform, in case you invite
                                                        others to use the Services, we’ll store those contacts on our servers. We also collect
                                                        information on how you use the Services, including actions you take in your account
                                                        (such as sharing, editing, viewing, creating, and moving files or folders). We use this
                                                        information to provide, improve and promote our Services and protect Platform users. </p></li>
                                                <li><p>4.1.6. <b>User Data:</b> Our Services are designed as a personalized and straightforward way to store
                                                your files, documents, photos, comments, messages, and so on (‘<b>User Data</b>’), collaborate
                                                with others, and work across multiple devices and services. To make that possible, we
                                                store, process, and transmit User Data and its information. This related information
                                                includes your profile information, which makes it easier to collaborate and share User
                                                Data with others, as well as the size of the file, the time it was uploaded, collaborators,
                                                and usage activity. </p></li>
                                            </ul>
                                            </li>

                                            <li><p>4.2. Personal Information, Non-Personal Information, Financial Information, Information from ThirdParties, Usage Information and User Data hereinafter collectively be referred to as “<b>Information</b>” </p></li>
                                    </ul>
                                </li>
                                


                                <li>
                                    <h6>5. Collection of Information </h6>

                                    <ul>
                                        <li><p>5.1. The Company may collect Information from you when you (a) register on the Platform; (b) update
                                                or change personal details in your account; (c) use the Platform for any of the services being
                                                offered thereon; and (d) when you carry out transactions on the Platform. </p></li>
                                        <li><p>5.2. You hereby acknowledge and agree that all Information is provided by you to the Company
                                                voluntarily and the Information provided by you is not subject to any undue influence.</p></li>
                                        <li><p>5.3. The Company may use cookies to monitor the Platform usage including, without limitation, to
                                                provide useful features to simplify your experience when you return to the Platform, like
                                                remembering your login id, Information and to deliver relevant content based on your preferences,
                                                usage patterns and location. </p></li>
                                        <li><p>5.4. You may use the Platform without providing the Company any Personal Information about
                                            yourself. However, you may not be able to access certain services of the Platform in case you
                                            choose to do so.</p></li>
                                    </ul>
                                </li>

                                <li>
                                    <h6>6. Purpose or Use of Information </h6>
                                    <ul>
                                        <li><p>6.1. Our primary purpose in collecting Information is to provide you with a secure, smooth, efficient,
                                                and customized experience. We may use Information to; provide services, conduct identity
                                                verification and customer support, manage your account, process transactions and send
                                                notifications about your transactions, resolve disputes, resolve any glitches on the Platform
                                                including addressing any technical problems and troubleshooting problems, including preventing
                                                potentially prohibited or illegal activities, and enforcing our user agreement. We also use the
                                                Information in order to customize, measure, and improve the Platform’s services and the content,
                                                layout, and operation of Platform, as well as to contact you at any telephone number by placing a
                                                voice call or through text (SMS) or email messaging and compare information for accuracy and
                                                verify it with third parties.</p></li>
                                        <li><p>6.2. Company may use the Information to monitor your use of the services and may review and analyse
                                            the Information provided by you to provide you with customized service.</p></li>
                                        <li><p>6.3. The Company may use your Non-Personal Information for internal business purposes, such as data
                                            analysis, research, developing new products and/or features, enhancing and improving existing
                                            products and services and identifying usage trends. </p></li>
                                        <li><p>6.4. Subject to and in accordance with applicable laws, the Company has the right to use your
                                            Information for the purpose of conducting promotional/marketing related activities on the Platform,
                                            including but not limited to, using your Personal Information for making posters/banners to
                                            promote the services of the Company.</p></li>
                                        <li><p>6.5. When you send an email message or otherwise contact the Company through its Platform, the
                                            Company may use the Information provided by you to respond to your communication by way of
                                            SMS, Whatsapp, Facebook, Instagram, Messenger and LinkedIn. The Company may also archive
                                            such Information and/or use it for future communications with you to inform you regarding
                                            updates, newsletters, offers, new services and promotions.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>7. Information Sharing</h6>

                                    <ul>
                                        <li><p>7.1. The Information is made accessible to employees, agents or partners and third-parties only on a
                                            need-to-know basis. </p></li>
                                        <li><p>7.2. The Company does not rent, sell, or share Information with other people or with other nonaffiliated entities, except with your consent, to provide services you have requested for or under the
                                            following circumstances:</p>

                                        <ul class="ml-4">
                                            <li><p>7.2.1. The Company may engage third party vendors and/or contractors to perform certain
                                                    support services, who may have limited access to Information. </p></li>
                                            <li><p>7.2.2. In order to process your transactions, the Company may direct you to a payment gateway
                                                    service provider of its own choice, which may have access to the Information provided by
                                                    you while making such payment.</p></li>
                                            <li><p>7.2.3. The Company may share Information with government authorities in response to
                                                subpoenas, court orders, or other legal processes; to establish or exercise legal rights; to
                                                defend against legal claims; or as otherwise required by law. This may be done in
                                                response to a law enforcement agency's request.</p></li>
                                        </ul>
                                    </li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>8. Third-Party Service Providers </h6>

                                    <ul>
                                        <li><p>8.1. The Company may engage third-party vendors and/or contractors to perform certain support
                                                services for the Company, including, without limitation, fulfilment of your transactions, software
                                                maintenance services, advertising and marketing services, web hosting services and such other
                                                related services which the Company requires to provide its services efficiently. These third parties
                                                may have limited access to Information. If they do, this limited access is provided so that they may
                                                perform these tasks for the Company, and they are not authorised by the Company to otherwise use
                                                or disclose Information, except to the extent required by law. The Company does not make any
                                                representations concerning the privacy practices or policies, or terms of use of such third-party
                                                vendors and/or contractors, nor does it control or guarantee the accuracy, integrity, or quality of the
                                                information, data, text, software, music, sound, photographs, graphics, videos, messages or other
                                                materials available on such websites of such third-party vendors and/or contractor. The inclusion or
                                                exclusion does not imply any endorsement by the Company of the website, the website's provider,
                                                or the information on such website.</p></li>
                                        <li><p>8.2. The Platform may contain links and interactive functionality interacting with the websites of third
                                                parties. The Company is not responsible for and has no liability for the functionality, actions,
                                                inactions, privacy settings, privacy policies, terms, or content of any such websites. Before
                                                enabling any sharing functions to communicate with any such websites or otherwise visiting any
                                                such websites, the Company strongly recommends that you review and understand the terms and
                                                conditions, privacy policies, settings, and information-sharing functions of each such third-party
                                                website.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>9. How Do We Protect & Store User Information?</h6>

                                    <ul>
                                        <li><p>9.1. The Company has taken adequate measures to protect the security of Information and to ensure that
                                                your choices for its intended use are honoured. The Company takes robust precautions to protect
                                                your data from loss, misuse, unauthorised access or disclosure, alteration, or destruction.</p></li>
                                        <li><p>9.2. We store and process user information on our computers in the world where our facilities are
                                            located. We protect the information using physical, technical, and administrative security measures
                                            to reduce the risks of loss, misuse, unauthorised access, disclosure and alteration. Some of the
                                            safeguards we use include firewalls and data encryption, physical access controls and following
                                            general data protection regulation (GDPR) protocol at our data centres and information access
                                            authorisation controls. At the same time, we formulate a user information security incident
                                            emergency plan and regularly organise relevant internal personnel to carry out emergency
                                            corresponding training and drills to master the procedures of job responsibilities and emergency
                                            response strategies. In addition to our efforts to ensure the security of your user data storage and
                                            processing, you should not disclose your Login Credentials or account information to anyone to
                                            protect your personal data. The company will not ask for your Login Credentials or any personal
                                            information through email or SMS. Whenever you log in to Platform, mainly when you use
                                            someone else's computer or a public internet terminal, please remember to click and quit after the
                                            operation. Your efforts and assistance are helpful for us in protecting your Information.</p></li>
                                        <li><p>9.3. If you suspect any unauthorised use of your account, you must immediately notify the Company by
                                                emailing <a href="mailto:info@bizionictech.com.ai.">info@bizionictech.com.ai.</a> You shall be liable to indemnify the Company for any loss
                                                suffered by the Company due to such unauthorised use of your account.</p></li>
                                        <li><p>9.4. The Company shall not be held liable or responsible for any loss or theft of Information due to
                                                unauthorised access to your device through which you use the Platform or other reasons solely
                                                attributable to you. Further, the Company shall not be responsible for any breach of security or for
                                                any actions of any third parties/vendors or events that are beyond the Company’s reasonable
                                                control, including but not limited to acts of government, computer hacking, unauthorised access to
                                                computer data and storage device, computer crashes, breach of security and encryption, poor
                                                quality of internet service or telephone service of the user, etc. </p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>10. Minor</h6>

                                    <ul>
                                        <li><p>The Company does not intend to attract anyone under the relevant age of consent to enter into
                                                binding legal contracts under the laws of their respective jurisdictions. The Company does not
                                                intentionally or knowingly collect Personal Information through the Platform from anyone under
                                                that age. The Company encourages parents and guardians to be involved in the online activities of
                                                minors to ensure that no Personal Information is collected from a minor without their prior consent.
                                                If you are using the Platform on behalf of someone else, including but not limited to on behalf of
                                                your minor child/children/employer, you represent and warrant that you are authorised by such
                                                person to accept this Policy on their behalf and to consent on behalf of such person to the
                                                Company’s use of such person’s Personal Information as described in this Policy.</p></li>
                                    </ul>
                                </li>

                                <li>
                                    <h6>11. Compliance with Laws for Users Outside India</h6>

                                    <ul>
                                        <li><p>11.1. While we strive to ensure compliance with applicable laws and regulations, we need more time to
                                                address the specific laws of every region. However, we are committed to protecting all our users'
                                                privacy and Personal Information.</p></li>
                                        <li><p>11.2. <b>Acceptance of Privacy Policy:</b> By accessing and using our services as a user outside India, you
                                                acknowledge and agree to the terms of this Policy and our data practices.</p></li>
                                        <li><p>11.3. <b>Data Subject Rights:</b> As a user outside India, you may have certain rights regarding your personal
                                            information under the applicable laws of your region. While we strive to respect these rights to the
                                            extent required by law, please note that our ability to address specific legal requirements may be
                                            limited. We will, however, make reasonable efforts to assist you in exercising your rights as
                                            permitted by applicable laws.</p></li>
                                        <li><p>11.4. <b>Compliance with Local Laws:</b> While we endeavour to comply with applicable laws and
                                            regulations, including privacy and data protection laws, in all regions we operate, it is essential to
                                            note that specific laws may have extraterritorial applications. We encourage users outside India to
                                            familiarise themselves with the local laws that may apply to their Personal Information and to
                                            assess the risks associated with using our services.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>12. How Do We Share User Information with Other Parties?</h6>
                                    <ul>
                                        <li><p>12.1. The Company maintains your Information in electronic form on its devices and equipment. The
                                                Information is made accessible to employees, agents or partners and third parties only on a need-toknow basis.</p></li>
                                        <li><p>12.2. We may share your user information with the following:</p>
                                    
                                            <ul class="ml-4">
                                                <li><p>12.2.1. A service provider that has a contractual relationship with us to assist us in our business
                                                    operations, such as prevention of fraud, collection, marketing and technical services. Our
                                                    contract stipulates that these service providers may only use your Information to provide
                                                    services to us and not use your information for their own benefit.</p></li>
                                                <li><p>12.2.2. Other private third parties may be located in countries where user information laws are
                                                    more relaxed than in your country or region. By submitting your information, you
                                                    expressly agree to share, store and process such information with third parties located in
                                                    other jurisdictions. The company will not sell or rent your information to third parties for
                                                    marketing purposes. It will only share your Information with third parties in accordance
                                                    with the provisions of this Policy. If you open an account on Platform directly on a thirdparty website or through a third-party application, Platform is not responsible for the
                                                    content or information specifications of such third parties.</p></li>
                                                <li><p>12.2.3. In cases where we have your permission to provide services that you have requested and
                                                        such Personal Information is necessary to provide these services, the Information may be
                                                        shared with our business associates, including the business partners and other third-party
                                                        service suppliers. We may, however, share consumer information on an aggregate with
                                                        our partners or third parties where we deem necessary. In addition, we may use this
                                                        information for promotional offers.</p></li>
                                                <li><p>12.2.4. In order to process your transactions, Company may direct you to a payment gateway
                                                        service provider of its own choice, which may have access to the Information provided by
                                                        you while making such payment.</p></li>
                                                <li><p>12.2.5. Additionally, in the event of an audit, reorganisation, merger, sale, joint venture,
                                                        assignment, transfer or other disposition of all or any portion of our business, assets or
                                                        stock (including in connection with any bankruptcy or similar proceedings), we may
                                                        share/transfer/assign the Information we have collected to the relevant third party.</p></li>
                                            </ul>
                                    
                                        </li>
                                        <li><p>12.3. Company reserves the right to collect and use your Information in accordance with the law
                                            irrespective of your consent, in connection with the following information; (i) directly related to
                                            national security and national defence security (ii) directly related to public safety, public health
                                            and other primary public interests (iii) directly related to criminal investigations, prosecution, trial
                                            and execution of judgements (iv) maintaining the safety as well as stability of the operation of
                                            services provided, such as failure to discover or dispose of products and services (v) enforce
                                            applicable terms and conditions, including investigation of potential violations thereof (vi) protect
                                            against imminent harm to our rights, property or safety, our users or the public as required or
                                            permitted by law; or (vii) to defend against legal claims; exceptional circumstances such as
                                            compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement
                                            agencies requiring such disclosure and any other such circumstances that are mandated by law.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>13. How to Access or Change Your User Information?</h6>

                                    <ul>
                                        <li><p>13.1. You can view and modify or delete your user information or close your account anytime by logging
                                                into your account and viewing your account settings and user information subject to the terms and
                                                conditions. You are responsible for the authenticity of the information you have filled out. You can
                                                also cancel your account through the Platform. If you cancel your account, we may still retain
                                                certain Information in your account. The Information you delete will not appear in your account.
                                                Still, this information will remain on the data storage platform of Platform to resolve disputes,
                                                eliminate problems, assist in any investigation, avoid fraud, and implement our user agreement or
                                                take other measures required or permitted by law.</p></li>
                                        <li><p>13.2. In the event you are a user in the EU or EEA, you will be asked to provide explicit and affirmative
                                            consent to the collection, processing, and sharing of your Personal Information, subject to
                                            withdrawal of your consent at any time on request. Under GDPR, EU/EEA residents have the
                                            following rights:</p>
                                        
                                        <ul class="ml-4">
                                            <li><p class="pb-1">13.2.1. To know the purpose of processing Personal Information.</p></li>
                                            <li><p class="pb-1">13.2.2. To know the status of Personal Information processed.</p></li>
                                            <li><p class="pb-1">13.2.3. Access the Personal Information that is processed.</p></li>
                                            <li><p class="pb-1">13.2.4. To get erased or rectified the Personal Information.</p></li>
                                            <li><p class="pb-1">13.2.5. Restrict the processing of Personal Information.</p></li>
                                            <li><p class="pb-1">13.2.6. Data portability of the Personal Information provided in respect of the Services</p></li>
                                            <li><p class="">13.2.7. Opt-out option from processing the Personal Information (unless Company has otherwise
                                                    compelling legitimate grounds).</p></li>
                                        </ul>
                                        </li>
                                        <li><p>13.3. The abovementioned rights can be exercised by EU/EEA residents by contacting us at <a href="mailto:privacy@bizionictech.com">privacy@bizionictech.com</a>.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>14. Marketing</h6>
                                    <ul>
                                        <li><p>The company will not sell or rent your Information to third parties for marketing purposes of third
                                                parties without your explicit consent. We may combine your information with the information we
                                                collect from other companies and use it to improve and personalise our services as well as content
                                                and advertising.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>15. Site Security</h6>
                                    <ul>
                                        <li><p>As a condition to your use of Platform, you agree that you will not take any action intended to: (i)
                                                access data that is not intended for you; (ii) invade the privacy of, obtain the identity of, or obtain
                                                any Personal Information about any Company’s customer user of this Platform; (iii) probe, scan or
                                                test the vulnerability of the Platform or breach security or authentication measures without proper
                                                authorisation; (iv) attempt to interfere with service to any user, host or network or otherwise
                                                attempt to disrupt our business, including, without limitation, via means of submitting a virus to the
                                                Platform, overloading, "flooding," "spamming," "mail bombing", “phishing”, “spoofing”, “identity
                                                theft”, “hacking”, “cyberstalking”, “malvertising” or "crashing" the Platform; or (v) send
                                                unsolicited mail, including promotions and/or advertising of products and services.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>16. Security and Protection of Your Platform Account</h6>
                                    <ul>
                                        <li><p>16.1. In order to protect your account from any harm, loss and misuse of your Information, appropriate
                                                physical, administrative, technical and electronic security measures have been implemented.
                                                However, these may be varied according to the sensitivity of such information.</p></li>
                                        <li><p>16.2. Furthermore, the Company does not guarantee that these measures are perfect or impenetrable and
                                            that Information will remain secure. We appreciate your help in safeguarding the integrity of your
                                            own and others’ privacy. In case of any complaint, suspicion of loss or misuse of any of your
                                            Information, you are solely responsible to inform Company of any such event, and the burden of
                                            proof lies on you to substantiate your allegations.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>17. Important Notice</h6>
                                    <ul>
                                        <li><p>Some of our websites link to other sites created and maintained by other public and/or private
                                                sector organisations. We provide these links solely for your information and convenience. When
                                                you link to an outside website, you are leaving our Platform, and our Policy no longer applies.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>18. Data Retention</h6>
                                    <ul>
                                        <li><p>Company shall be entitled to retain your Personal Information for our records for such period of
                                                time as may be required by applicable laws after the deletion of your account on the Platform
                                                and/or completion of services, and such Personal Information shall be used by us only in
                                                consonance with this Policy, including for compliance with legal obligations, resolving of disputes
                                                and enforcing any agreements executed between us. </p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>19. Limitation of Liability</h6>
                                    <ul>
                                        <li><p>19.1. The Company shall not be liable to you for any loss of profit, anticipated savings, goodwill,
                                            reputation or business opportunities or any direct or indirect, incidental, economic, compensatory,
                                            punitive, exemplary or consequential losses arising out of performance or non-performance of its
                                            obligations under this Policy</p></li>
                                        <li><p>19.2. The Company is not responsible for any actions or inactions of any third parties that receive your Information</p></li>
                                        <li><p>19.3. Notwithstanding anything contained in this Privacy Policy or elsewhere, the Company shall not be
                                                held responsible for any loss, damage or misuse of your Information if such loss, damage or misuse
                                                is attributable to a Force Majeure Event and/or any third party. The term “Force Majeure Event”
                                                shall mean any event that is beyond the reasonable control of the Company and shall include,
                                                without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes, lockouts
                                                or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking,
                                                civil disturbances, unauthorised access to computer data and storage device, computer crashes,
                                                breach of security and encryption, epidemic, pandemic or national/state lockdown due to any
                                                reason and any other similar events not within the control of the Company and which the Company
                                                is not able to overcome.</p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>20. OPT-OUT</h6>
                                    <ul>
                                        <li><p>Once you register as a user on the Platform, you may receive multimedia text messages as SMS,
                                                WhatsApp, Facebook Messenger, Instagram, Telegram and phone calls from the Company on the
                                                registered mobile number and e-mails on your registered e-mail address. These messages, e-mails
                                                and calls could relate to your registration, transactions you carry out through the Platform and
                                                promotions that the Company undertakes. You have the option to 'opt-out' of all Company’s
                                                newsletters and other general email marketing communications by way of links provided at the
                                                bottom of each mailer. The Company respects your privacy, and in the event that you choose not to
                                                receive such mailers, the Company shall take all adequate steps to remove you from such lists.
                                                However, you cannot opt-out of receiving administrative messages, customer service responses or
                                                other transactional communications. </p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>21. Dispute Resolution and Governing Law</h6>
                                    <ul>
                                        <li><p>21.1. If there is a grievance or concern in respect of this Privacy Policy or the services provided by the
                                                Company, you are requested to email us details of the same at privacy@bizionictech.com.ai. Any
                                                concern shall be sought to be addressed by Company, and in the event of any dispute, you and
                                                Company shall endeavour to resolve the dispute amicably.  </p></li>
                                        <li><p>21.2. This Policy shall be governed and construed under the laws of India without giving effect to the
                                                conflict of laws principle, and the courts of Hyderabad shall have exclusive jurisdiction.  </p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>22. Grievance Redressal Mechanism</h6>
                                    <ul>
                                        <li><p>The company has constituted an appropriate grievance redressal mechanism within the organisation
                                                to resolve users' grievances. The company has designated an officer to redress the genuine
                                                grievances of the users of the Platform, the details of whom are stated herein below (“<b>Grievance
                                                Redressal Officer</b>”). </p></li>
                                    </ul>
                                </li>


                                <li>
                                    <h6>23. Grievance Redressal Officer</h6>
                                    <ul>
                                        <li><p>23.1. Any complaints, abuse or concerns with regards to content and/or comment and/or breach of this
                                            Policy shall be immediately informed to the designated Grievance Redressal Officer as mentioned
                                            below via writing or through email:</p></li>
                                        <li><p>23.2. <u>Details of the Grievance Redressal Officer:</u> </p>
                                    
                                        <ul class="ml-4">
                                            <li><p class="p-0"><u><b>Name</b> : Syed Hussaini</u></p></li>
                                            <li><p class="p-0"><u><b>Designation</b> : Grievance Redressal Officer</u></p></li>
                                            <li><p class="p-0"><u>Email: <a href="mailto:privacy@bizionictech.com">privacy@bizionictech.com</a></u></p></li>
                                            <li><p class="p-0"><u>Phone: +91 98593 60184</u></p></li>
                                            <li><p class="p-0"><u>Address: 3rd Floor, Office No 1A, 6-3-1090/B/4, The Grand Building, KFC Building, Raj Bhavan<br>
                                                Rd, Somajiguda, Hyderabad, Telangana 500082</u></p></li>
                                        </ul>
                                    </li>
                                    </ul>
                                </li>


                            </ul>

                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>
                </div>
            </div>
        </div>
   </div>